### ISSUE TITLE
Missing compatible node-ios-device library

### ISSUE THREAD

**Issue by nghiadhd** [appcelerator/node-ios-device#12]
My node is v5.0.0 (module API v47)

However when I inject the node-ios-device, I got incompatible issue

Missing compatible node-ios-device library
    at /Volumes/Data/Projects/krypton/coms/desktop/node_modules/node-ios-device/ios-device.js:58:21

I debug and see that
modulesVer === 46
But node binary is "node_ios_device_v47.node"

I tried to switch to node v4.2.2 (module API v46) and your module works well. But in your home page states that node-ios-device is currently compatible with node v5, so could you please review it and make your module compatible with the latest node

**Comment by cb1kenobi** [comment]
@nghiadhd It certainly is compatible with Node.js 5.0. You see, `node_ios_device_v47.node` is the Node.js 5.0 compatible binary. `node_ios_device_v46.node` is the Node.js 4.x compatible binary. If you `npm install node-ios-device` when Node.js 4.2.2 is installed, then it will build `node_ios_device_v46.node`. If you then install Node.js 5.0, node-ios-device will fail because you need to rebuild node-ios-device so that it generates the compatible `node_ios_device_47.node`.

I've made a convenient Makefile that builds node-ios-device for all supported Node.js versions. Simply run `make` from the `node_modules/node-ios-device` folder. I will probably want to use the latest Node.js version before running this.
