### ISSUE TITLE
Unable to install vcremote

### ISSUE THREAD

**Issue by hitek123** [appcelerator/node-ios-device#27]
Trying to install vcremote on my mac:
MARKS-MAC-MINI:~ mark$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12
BuildVersion:	16A323
MARKS-MAC-MINI:~ mark$ node -v
v7.1.0
MARKS-MAC-MINI:~ mark$ npm -v
4.0.2
MARKS-MAC-MINI:~ mark$ npm list node-pre-gyp
mark@1.0.0 /Users/mark
└── node-pre-gyp@0.6.31 

I've attached the output as well as the log.

[npm-debug.log.zip](https://github.com/appcelerator/node-ios-device/files/580820/npm-debug.log.zip)
[vcremote-install.log.zip](https://github.com/appcelerator/node-ios-device/files/580822/vcremote-install.log.zip)

**Comment by cb1kenobi** [comment]
How exactly does this have anything to do with `node-ios-device`?

**Comment by hitek123** [comment]
Just following the advise in the output:
Failed at the node-ios-device@0.5.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-ios-device package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-ios-device
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-ios-device

**Comment by cb1kenobi** [comment]
Yeah, this is not a `node-ios-device` issue.

`vcremote` uses a package called `vcremote-lib` which in turn uses `node-ios-device`. Further, it uses a really old version of `node-ios-device` and it's declaring `node-ios-device` a dependency instead of an optional dependency.

So, you should contact the author of `vcremote-lib` and tell them up update to the latest version and make `node-ios-device` an optional dependency.

**Comment by hitek123** [comment]
OK. Thank you very much.
