### ISSUE TITLE
iOS Device Trust Issue

### ISSUE THREAD

**Issue by an-rahulpandey** [appcelerator/node-ios-device#36]
Hi,

First of all thanks for the great library. However I am running into an issue - 
It doesn't work unless device is trusted. Once I trust the device, I have to reconnect the device to get the details, is there a direct way to handle this. Currently I am using this - /

```
const handle = iosDevice
	.trackDevices()
	.on('devices', console.log);
});
```

**Comment by cb1kenobi** [comment]
Thanks for reporting this issue. I haven't run into this yet.

Since `node-ios-device` relies on `MobileDevice.framework`, I'm not sure if it exposes a property indicated if the device is trusted or not. If it does, then we certainly can try to fix this.

Question: is there a way to "untrust" or "forget" a trusted device so that I can repeatably test this?

**Comment by an-rahulpandey** [comment]
Yes,  Go to Settings > General > Reset > Reset Location & Privacy. It will reset all the trusted pc/mac list.

**Comment by cb1kenobi** [comment]
Brilliant! OK, I'll add this to my radar and I'll get to it as soon as I have time. Thanks!

**Comment by an-rahulpandey** [comment]
Thanks for replying so fast, will wait in the meantime 🍺

**Comment by an-rahulpandey** [comment]
Is there any update on this?

**Comment by cb1kenobi** [comment]
Nope. It's on my radar. I don't have any time in my schedule to fix this. It could be several weeks more before I can look at this.

**Comment by cb1kenobi** [comment]
In node-ios-device@2.0.0, the device properties now includes a `trustedHostAttached` property that can be used to filter untrusted devices.
